@startuml King
[*] --> Wait : created
Wait --> Chosen : clicked on
Chosen --> Move : clicked on\n avaiable square
Chosen --> Wait : cancel
Move --> Wait
Wait --> Check : checked
Check --> Wait : unchecked
Check --> Chosen : clicked on
Chosen --> Check : cancel
Check --> Move : clicked on\n avaiable square
Check --> [*] : made illegal move
Wait --> [*] : checkmate/stalemate
@enduml