@startuml
class Spot{
  piece: Piece
  x: Number
  y: Number
}

class Board{
  rows: Number
  cols: Number
  boxes: Spot[][]
  void initialize()
  void renderBoard()
}

class Piece{
  name: String
  imgUrl: String
  isWhite: Boolean
  isKilled: Boolean
  Boolean canMove(Board board,Spot start, Spot end)
  {x:number, y:number}[] getSpotsCanMove(startX: number, startY: number)
}

class Move{
  player: Player
  start: Spot
  end: Spot
  pieceMoved: Piece
  pieceKilled: Piece
}

class Game{
  status: String
  board: Board
  players: Player[]
  currentTurn: Player
  moves: Move[]

  void initialize()
  void startGame()
  void endGame()
  void pauseGame()
  void resetGame()
  void playerMove(player: Player, startX: Number, startY: Number, endX: Number, endY: Number)
  void goToPreviousStep(player: Player)
}

class Player{
  name: String
  isWhiteSide: Boolean
}

class HumanPlayer{
  score: Number
  void calculatingScore()
}

class ComputerPlayer{}


class King{}
class Bishop{}
class Knight{}
class Pawn{}
class Queen{}
class Rook{}





Piece <|-- King
Piece <|-- Bishop
Piece <|-- Knight
Piece <|-- Pawn
Piece <|-- Queen
Piece <|-- Rook

Player <|-- HumanPlayer
Player <|-- ComputerPlayer

@enduml
