@startuml ChessBoard
skinparam groupInheritance 2

class ChessBoard {
    + cells

    + create()
    + addSquareToRow()
    + changeSquareColor()
}
class ChessPiece {
    + id
    + name 
    + url 
    + setPiece() 
    + isChosen() 
    + recommendMoves() 
}


ChessBoard <-- ChessPiece
ChessBoard <-- Controller
note left of Controller: implement later

ChessPiece <|-- Pawn 
ChessPiece <|-- Rook 
ChessPiece <|-- Knight 
ChessPiece <|-- Bishop 
ChessPiece <|-- Queen  
ChessPiece <|-- King 
@enduml